#
# TODO: Move `libmongoclient.a` to /usr/local/lib so this can work on production servers
#

CC := g++ -std=c++11 # This is the main compiler
# CC := clang --analyze # and comment out the linker last line for sanity
SRCDIR := src
BUILDDIR := build
TARGET := bin/insomnia

SRCEXT := cpp
SOURCES := $(shell find $(SRCDIR) -type f -name *.$(SRCEXT))
OBJECTS := $(patsubst $(SRCDIR)/%,$(BUILDDIR)/%,$(SOURCES:.$(SRCEXT)=.o))
CFLAGS := -g # -Wall
#LIB := -lboost_regex -lboost_log -pthread  -L lib -lboost_thread-mt -lboost_filesystem-mt -lboost_system-mt #-lmongoclient
#LIB := -pthread -lmongoclient -L lib -lboost_thread-mt -lboost_filesystem-mt -lboost_system-mt
LIB := -pthread -L lib -lboost_log-mt -lboost_log_setup -lboost_regex  -lboost_thread-mt -lboost_filesystem-mt -lboost_system-mt -lboost_date_time
INC := -Iinclude
BADL := -DBOOST_LOG_DYN_LINK

$(TARGET): $(OBJECTS)
	@echo " Linking..."
	@echo " $(CC) $^ $(BADL) -o $(TARGET) $(LIB)"; $(CC) $^ $(BADL) -o $(TARGET) $(LIB)

$(BUILDDIR)/%.o: $(SRCDIR)/%.$(SRCEXT)
	@mkdir -p $(BUILDDIR)
	@echo " $(CC) $(CFLAGS) $(INC) $(BADL) -c -o $@ $<"; $(CC) $(CFLAGS) $(INC) $(BADL) -c -o $@ $<

clean:
	@echo " Cleaning..."; 
	@echo " $(RM) -r $(BUILDDIR) $(TARGET)"; $(RM) -r $(BUILDDIR) $(TARGET)

# Tests
tester:
	$(CC) $(CFLAGS) test/tester.cpp $(INC) $(LIB) -o bin/tester

# Spikes
ticket:
	$(CC) $(CFLAGS) spikes/ticket.cpp $(INC) $(LIB) -o bin/ticket

.PHONY: clean