SET ( Boost_FIND_REQUIRED TRUE )
SET ( Boost_USE_MULTITHREADED ON )
SET ( Boost_USE_STATIC_LIBS OFF )
SET ( Boost_USE_STATIC_RUNTIME OFF )
SET ( PGSQL_FIND_REQUIRED TRUE )
SET ( PISTACHE_FIND_REQUIRED TRUE )
SET ( PQXX_FIND_REQUIRED TRUE )
SET ( THREADS_FIND_REQUIRED TRUE )

IF ( NOT WIN32 )
    SET ( THREADS_PREFER_PTHREAD_FLAG TRUE )
ENDIF (  )


### Boost ###
FIND_PACKAGE (Boost 1.55.0
    COMPONENTS
        date_time filesystem log log_setup regex system thread
    )
INCLUDE_DIRECTORIES ( SYSTEM ${BOOST_INCLUDE_DIRS} )


### pgSQL ###
FIND_PACKAGE ( pgSQL )
INCLUDE_DIRECTORIES ( SYSTEM ${PGSQL_INCLUDE_DIR} )


### Pistache ###
FIND_PACKAGE ( Pistache )
INCLUDE_DIRECTORIES ( SYSTEM ${PISTACHE_INCLUDE_DIR} )

### jwt ###
FIND_PACKAGE ( jwt )
INCLUDE_DIRECTORIES ( SYSTEM ${JWT_INCLUDE_DIR} )

### pqxx ###
FIND_PACKAGE ( pqxx )
INCLUDE_DIRECTORIES ( SYSTEM ${PQXX_INCLUDE_DIR} )


### Threads ###
FIND_PACKAGE ( Threads )
IF ( NOT THREADS_FOUND )
    IF ( THREADS_FIND_REQUIRED )
        MESSAGE ( FATAL_ERROR "Could not find Threads" )
    ENDIF (  )
ENDIF ( )
